package kafka_constants

const (
	PAS_EVENT                      = "PAS_EVENT"
	RANKING_PARAM_EVENT            = "RANKING_PARAM_EVENT"
	STORE_PRODUCT_PROPERTIES_EVENT = "STORE_PRODUCT_PROPERTIES_EVENT"
	BROWSE_SP_RANKING_EVENT        = "BROWSE_SP_RANKING_EVENT"
	PV_L4_ATTRIBUTE_EVENT          = "PV_L4_ATTRIBUTE_EVENT"
	STORE_PRODUCT_TAGS_EVENT       = "STORE_PRODUCT_TAGS_EVENT"
	PVID_CITYID_TAGS_EVENT         = "PVID_CITYID_TAGS_EVENT"
)
